export interface LigDashboardDataModel    {
    "product_code": number // "7211251",
    "qrcode_status": string // "REDEEMED",
    "mobile_no": number //"6000028845",
    "product_name":string //"MAK 4T SCOOTECH NXT 800 ML Case",
    "sap_cc_number": string //"",
    "NAME": string //"",
    "txn_count": number //"1",
    "txn_amount": number //"40.0",
    "pincode": number //"785001",
    "state": string  //"ASSAM",
    "region": string //"",
    "taluka": string //"Jorhat",
    "district": string //"Jorhat",
    "user_persona": string //"lubes_mechanic",
    "SALES_OFFICE_NAME": string  //"",
    "SALES_OFFICE_CODE": string //"",
    "STATE_NAME": string //"",
    "REGION_NAME": string //"",
    "SALES_GROUP_NAME": string //"",
    "PRODUCT_NAME": string //"MAK 4T SCOOTECH NXT 800 ML Case",
    "PRODUCT_CODE": number //"7211251",
    "PRODUCT_BRAND": string //"SCOOTECH N",
    "date": string //"2023-08",
    "sap_cc_number_cp": string //""
    [key:string] : string | number
}

export const LigDashboardAllHeaders =
[
 "product_code",
 "qrcode_status",
 "mobile_no",
 "product_name",
 "sap_cc_number",
 "NAME",
 "txn_count",
 "txn_amount",
 "pincode",
 "state",
 "region",
 "taluka",
 "district",
 "user_persona",
 "SALES_OFFICE_NAME",
 "SALES_OFFICE_CODE",
 "STATE_NAME",
 "REGION_NAME",
 "SALES_GROUP_NAME",
 "PRODUCT_NAME",
 "PRODUCT_CODE",
 "PRODUCT_BRAND",
 "date",
 "sap_cc_number_cp"
]

export const LigDashboardTableViewHeaders =
[
    "region",
    "SALES_OFFICE_NAME",
    "SALES_GROUP_NAME",
    "sap_cc_number",
    "NAME",
    "user_persona",
    "mobile_no",
    "PRODUCT_CODE",
    "PRODUCT_NAME",
    "pincode",
    "taluka",
    "district",
    "state",
    "txn_count",
    "txn_amount",
]
//LigDashboardDataModelHeaders
export const LigDashboardTableHeaders = LigDashboardTableViewHeaders;

export const LigDashboardTableHeadersApiMapping: Map<string,string> = new Map([
    ['region','BI Region'],
    ['SALES_OFFICE_NAME','BI Territory'],
    ['SALES_GROUP_NAME','BI Sales Area'], 
    ['sap_cc_number','Channel Partner'], 
    ['NAME','BU Primary customer name'],
    ['user_persona','LIG User Persona'],
    ['mobile_no','LIG Mobile number'],
    ['PRODUCT_CODE','LIG Product Code'], 
    ['PRODUCT_NAME','LIG Product Name' ],
    ['pincode','LIG PinCode' ],
    ['taluka','LIG Taluka'],
    ['district','LIG District' ],
    ['state','LIG State' ],
    ['txn_count','Coupon count'],
    ['txn_amount','Coupon amount' ]
])


const x =
[
    "region",
    "SALES_OFFICE_NAME",
    "SALES_GROUP_NAME",
    "sap_cc_number",
    "NAME",
    "user_persona",
    "mobile_no",
    "PRODUCT_CODE",
    "PRODUCT_NAME",
    "pincode",
    "taluka",
    "district",
    "state",
    "txn_count",
    "txn_amount",
]

export const SampleLigDashboardSnippetData : Array <LigDashboardDataModel> = [ {
    "product_code": +"7211251",
    "qrcode_status": "REDEEMED",
    "mobile_no": +"6000028845",
    "product_name": "MAK 4T SCOOTECH NXT 800 ML Case",
    "sap_cc_number": "",
    "NAME": "",
    "txn_count": +"1",
    "txn_amount": +"40.0",
    "pincode": +"785001",
    "state": "ASSAM",
    "region": "",
    "taluka": "Jorhat",
    "district": "Jorhat",
    "user_persona": "lubes_mechanic",
    "SALES_OFFICE_NAME": "",
    "SALES_OFFICE_CODE": "",
    "STATE_NAME": "",
    "REGION_NAME": "",
    "SALES_GROUP_NAME": "",
    "PRODUCT_NAME": "MAK 4T SCOOTECH NXT 800 ML Case",
    "PRODUCT_CODE": +"7211251",
    "PRODUCT_BRAND": "SCOOTECH N",
    "date": "2023-08",
    "sap_cc_number_cp": ""
},
{
    "product_code": +"7251851",
    "qrcode_status": "REDEEMED",
    "mobile_no": +"6000028845",
    "product_name": "MAK 4T SCOOTECH 10W30 800ML",
    "sap_cc_number": "",
    "NAME": "",
    "txn_count": +"13",
    "txn_amount": +"260.0",
    "pincode": +"785001",
    "state": "ASSAM",
    "region": "",
    "taluka": "Jorhat",
    "district": "Jorhat",
    "user_persona": "lubes_mechanic",
    "SALES_OFFICE_NAME": "",
    "SALES_OFFICE_CODE": "",
    "STATE_NAME": "",
    "REGION_NAME": "",
    "SALES_GROUP_NAME": "",
    "PRODUCT_NAME": "MAK 4T SCOOTECH 10W30 800ML",
    "PRODUCT_CODE": +"7251851",
    "PRODUCT_BRAND": "SCOOTECH",
    "date": "2023-08",
    "sap_cc_number_cp": ""
},
{
    "product_code": +"7265857",
    "qrcode_status": "REDEEMED",
    "mobile_no": +"6000028845",
    "product_name": "MAK 4T Plus (SL 20W-40) 1 lt X 12",
    "sap_cc_number": "",
    "NAME": "",
    "txn_count": +"12",
    "txn_amount": +"240.0",
    "pincode": +"785001",
    "state": "ASSAM",
    "region": "",
    "taluka": "Jorhat",
    "district": "Jorhat",
    "user_persona": "lubes_mechanic",
    "SALES_OFFICE_NAME": "",
    "SALES_OFFICE_CODE": "",
    "STATE_NAME": "",
    "REGION_NAME": "",
    "SALES_GROUP_NAME": "",
    "PRODUCT_NAME": "MAK 4T Plus (SL 20W-40) 1 lt X 12",
    "PRODUCT_CODE": +"7265857",
    "PRODUCT_BRAND": "4 T PLUS",
    "date": "2023-08",
    "sap_cc_number_cp": ""
}]