import {LigDashboardDataModel } from './lig-dashboard-data.model';

export const SampleLigDashboardSnippetData : Array <LigDashboardDataModel> = [ {
    "product_code": "7211251",
    "qrcode_status": "REDEEMED",
    "mobile_no": "6000028845",
    "product_name": "MAK 4T SCOOTECH NXT 800 ML Case",
    "sap_cc_number": "",
    "NAME": "",
    "txn_count": +"1",
    "txn_amount": +"40.0",
    "pincode": "785001",
    "state": "ASSAM",
    "region": "",
    "taluka": "Jorhat",
    "district": "Jorhat",
    "user_persona": "lubes_mechanic",
    "SALES_OFFICE_NAME": "",
    "SALES_OFFICE_CODE": "",
    "STATE_NAME": "",
    "REGION_NAME": "",
    "SALES_GROUP_NAME": "",
    "PRODUCT_NAME": "MAK 4T SCOOTECH NXT 800 ML Case",
    "PRODUCT_CODE": "7211251",
    "PRODUCT_BRAND": "SCOOTECH N",
    "date": "2023-08",
    "sap_cc_number_cp": ""
},
{
    "product_code": "7251851",
    "qrcode_status": "REDEEMED",
    "mobile_no": "6000028845",
    "product_name": "MAK 4T SCOOTECH 10W30 800ML",
    "sap_cc_number": "",
    "NAME": "",
    "txn_count": +"13",
    "txn_amount": +"260.0",
    "pincode": "785001",
    "state": "ASSAM",
    "region": "",
    "taluka": "Jorhat",
    "district": "Jorhat",
    "user_persona": "lubes_mechanic",
    "SALES_OFFICE_NAME": "",
    "SALES_OFFICE_CODE": "",
    "STATE_NAME": "",
    "REGION_NAME": "",
    "SALES_GROUP_NAME": "",
    "PRODUCT_NAME": "MAK 4T SCOOTECH 10W30 800ML",
    "PRODUCT_CODE": "7251851",
    "PRODUCT_BRAND": "SCOOTECH",
    "date": "2023-08",
    "sap_cc_number_cp": ""
},
{
    "product_code": "7265857",
    "qrcode_status": "REDEEMED",
    "mobile_no": "6000028845",
    "product_name": "MAK 4T Plus (SL 20W-40) 1 lt X 12",
    "sap_cc_number": "",
    "NAME": "",
    "txn_count": +"12",
    "txn_amount": +"240.0",
    "pincode": "785001",
    "state": "ASSAM",
    "region": "",
    "taluka": "Jorhat",
    "district": "Jorhat",
    "user_persona": "lubes_mechanic",
    "SALES_OFFICE_NAME": "",
    "SALES_OFFICE_CODE": "",
    "STATE_NAME": "",
    "REGION_NAME": "",
    "SALES_GROUP_NAME": "",
    "PRODUCT_NAME": "MAK 4T Plus (SL 20W-40) 1 lt X 12",
    "PRODUCT_CODE": "7265857",
    "PRODUCT_BRAND": "4 T PLUS",
    "date": "2023-08",
    "sap_cc_number_cp": ""
}]